//
// RT64_MATERIAL_ATTR(attributeFlag, field, luaName, type)
//

RT64_MATERIAL_ATTR(RT64_ATTRIBUTE_IGNORE_NORMAL_FACTOR,        ignoreNormalFactor,       "ignoreNormalFactor",       INT)
RT64_MATERIAL_ATTR(RT64_ATTRIBUTE_UV_DETAIL_SCALE,             uvDetailScale,            "uvDetailScale",            FLOAT)
RT64_MATERIAL_ATTR(RT64_ATTRIBUTE_REFLECTION_FACTOR,           reflectionFactor,         "reflectionFactor",         FLOAT)
RT64_MATERIAL_ATTR(RT64_ATTRIBUTE_REFLECTION_FRESNEL_FACTOR,   reflectionFresnelFactor,  "reflectionFresnelFactor",  FLOAT)
RT64_MATERIAL_ATTR(RT64_ATTRIBUTE_REFLECTION_SHINE_FACTOR,     reflectionShineFactor,    "reflectionShineFactor",    FLOAT)
RT64_MATERIAL_ATTR(RT64_ATTRIBUTE_REFRACTION_FACTOR,           refractionFactor,         "refractionFactor",         FLOAT)
RT64_MATERIAL_ATTR(RT64_ATTRIBUTE_SPECULAR_COLOR,              specularColor,            "specularColor",            COLOR3)
RT64_MATERIAL_ATTR(RT64_ATTRIBUTE_SPECULAR_SHINYNESS,          specularShinyness,        "specularShinyness",        FLOAT)
RT64_MATERIAL_ATTR(RT64_ATTRIBUTE_SOLID_ALPHA_MULTIPLIER,      solidAlphaMultiplier,     "solidAlphaMultiplier",     FLOAT)
RT64_MATERIAL_ATTR(RT64_ATTRIBUTE_SHADOW_ALPHA_MULTIPLIER,     shadowAlphaMultiplier,    "shadowAlphaMultiplier",    FLOAT)
RT64_MATERIAL_ATTR(RT64_ATTRIBUTE_DEPTH_BIAS,                  depthBias,                "depthBias",                INT)
RT64_MATERIAL_ATTR(RT64_ATTRIBUTE_SHADOW_RAY_BIAS,             shadowRayBias,            "shadowRayBias",            INT)
RT64_MATERIAL_ATTR(RT64_ATTRIBUTE_SELF_LIGHT_COLOR,            selfLightColor,           "selfLightColor",           COLOR3)
RT64_MATERIAL_ATTR(RT64_ATTRIBUTE_LIGHT_GROUP_MASK_BITS,       lightGroupMaskBits,       "lightGroupMaskBits",       MASK)
RT64_MATERIAL_ATTR(RT64_ATTRIBUTE_DIFFUSE_COLOR_MIX,           diffuseColorMix,          "diffuseColorMix",          COLOR_MIX)
RT64_MATERIAL_ATTR(RT64_ATTRIBUTE_DIFFUSE_INTENSITY,           diffuseIntensity,         "diffuseIntensity",         FLOAT)
RT64_MATERIAL_ATTR(RT64_ATTRIBUTE_SPECULAR_FACTOR,             specularFactor,           "specularFactor",           FLOAT)
RT64_MATERIAL_ATTR(RT64_ATTRIBUTE_SPECULAR_ECCENTRICITY,       specularEccentricity,     "specularEccentricity",     FLOAT)
RT64_MATERIAL_ATTR(RT64_ATTRIBUTE_BUMP_STRENGTH,               bumpStrength,             "bumpStrength",             FLOAT)
RT64_MATERIAL_ATTR(RT64_ATTRIBUTE_NORMAL_STRENGTH,             normalStrength,           "normalStrength",           FLOAT)
RT64_MATERIAL_ATTR(RT64_ATTRIBUTE_REFLECTION_COLOR,            reflectionColor,          "reflectionColor",          COLOR3)
RT64_MATERIAL_ATTR(RT64_ATTRIBUTE_SPECULAR_INTENSITY,          specularIntensity,        "specularIntensity",        FLOAT)
RT64_MATERIAL_ATTR(RT64_ATTRIBUTE_SELF_LIGHT_INTENSITY,        selfLightIntensity,       "selfLightIntensity",       FLOAT)
